### ISSUE TITLE
Need grammar check in README.md file.

### ISSUE THREAD

**Issue by Deeksha2501** [fossasia/open-event-theme#14]
Thre are some grammar issues in README.md file, most precisely two.
There is an extra comma in the introduction paragraph and in the License section an extra 'the' is needed.
Can I work on this issue?

**Comment by atulgawhane** [comment]
i want to work on this issue, please assign it to me

**Comment by Anand-Kumar-Singh** [comment]
I wanna to work on this issue.Please assign this issue to me

**Comment by Rudresh22** [comment]
Please assign this issue to me, I want to contribute on this issue.

**Comment by vennelakoilada362** [comment]
please assign this issue to me, 
I just want to contribute .

**Comment by adarshsinghk** [comment]
i want to work on this issue

**Comment by mariobehling** [comment]
Not priority
